return {
  id = "brackets",
  title = "Text Objects: Brackets",
  summary = "di{ da{ ci{ ca{ and di[ operate on brace and bracket pairs.",
  concept = "Text objects work on any bracket pair: { } for braces, [ ] for brackets, ( ) for parentheses. i means inside (keep the brackets), a means around (include them). They work across lines, which is perfect for code: di{ clears a struct literal, ci{ rewrites a block, da[ drops an array's brackets and contents.",
  exercises = {
    {
      id = "delete-inside-braces",
      instruction = "With the cursor on the '{', delete the inside of the braces (keep the braces) with di{.",
      initial_content = { 'cfg := Config{Host: "localhost"}' },
      cursor = { 1, 13 },
      validation = { type = "buffer", expected = { "cfg := Config{}" } },
      success_message = "di{ deletes the content inside a brace pair.",
      hints = {
        "Type d, i, and the open brace key.",
        "The braces themselves survive — that is 'inside'.",
      },
      solution = { keys = "di{", text = "Type di{." },
    },
    {
      id = "delete-around-braces",
      instruction = "With the cursor on the '{', delete the braces AND their content with da{.",
      initial_content = { "return { ok: true };" },
      cursor = { 1, 7 },
      validation = { type = "buffer", expected = { "return ;" } },
      success_message = "da{ deletes the brace pair plus its content.",
      hints = {
        "Type d, a, and the open brace key.",
        "This time the braces go too — that is 'around'.",
      },
      solution = { keys = "da{", text = "Type da{." },
    },
    {
      id = "change-inside-braces",
      instruction = "Bump the default: with the cursor on the '{', change what is inside with ci{: type ' version: 2 ' (keep the spaces), then <Esc>.",
      initial_content = { "export default { version: 1 };" },
      cursor = { 1, 15 },
      validation = { type = "buffer", expected = { "export default { version: 2 };" } },
      success_message = "ci{ deletes the inside and opens INSERT mode at its start.",
      hints = {
        "Type c, i, {, then ' version: 2 ' (with the spaces) and <Esc>.",
        "The opening brace stays put; the content is replaced.",
      },
      solution = { keys = "ci{ version: 2 <Esc>", text = "Type ci{, type ' version: 2 ', press <Esc>." },
    },
    {
      id = "change-around-braces",
      instruction = "With the cursor on the '{', replace the braces and their content with ca{: type 'null', then <Esc>.",
      initial_content = { "const wrapped = wrap({ inner: 1 });" },
      cursor = { 1, 21 },
      validation = { type = "buffer", expected = { "const wrapped = wrap(null);" } },
      success_message = "ca{ replaces the whole brace pair in one motion.",
      hints = {
        "Type c, a, {, then 'null' and <Esc>.",
        "The { inner: 1 } block becomes whatever you type.",
      },
      solution = { keys = "ca{null<Esc>", text = "Type ca{, type 'null', press <Esc>." },
    },
    {
      id = "delete-inside-brackets",
      instruction = "With the cursor on the '[', empty the array (keep the brackets) with di[.",
      initial_content = { 'const allowed = ["GET", "POST"];' },
      cursor = { 1, 16 },
      validation = { type = "buffer", expected = { "const allowed = [];" } },
      success_message = "di[ works on brackets exactly like it does on braces.",
      hints = {
        "Type d, i, and the open bracket key.",
        "Every bracket pair is a text object: {}, [], () and more.",
      },
      solution = { keys = "di[", text = "Type di[." },
    },
  },
}
