return {
  id = "change-case",
  title = "Change Case",
  summary = "gu and gU change the case of whatever a motion or text object covers.",
  concept = "U and ~ change the case of a selection or a single character, but the g-prefixed versions work with any motion: gU uppercases, gu lowercases. Pair them with w (word), $ (line end), g$ (visual line end), or a text object like i( for surgical case changes. Classic uses: unexporting a Go name, turning a constant into SCREAMING_SNAKE, fixing a log line.",
  exercises = {
    {
      id = "lowercase-word-with-guw",
      instruction = "The constant should be a plain variable. With the cursor on the 'M', lowercase the whole word with guw.",
      initial_content = { "MAX_ATTEMPTS = 5" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "max_attempts = 5" } },
      success_message = "guw lowercases from the cursor to the end of the word.",
      hints = {
        "Type g, u, w.",
        "gU is the uppercase twin.",
      },
      solution = { keys = "guw", text = "Type guw." },
    },
    {
      id = "uppercase-word-with-gUw",
      instruction = "The setting should be a module constant. With the cursor on the 'r' of 'retry_limit', uppercase that word with gUw.",
      initial_content = { "retry_limit = 5" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "RETRY_LIMIT = 5" } },
      success_message = "gUw uppercases a single word, leaving the rest alone.",
      hints = {
        "Type g, U, w.",
        "The motion after gU decides how much changes.",
      },
      solution = { keys = "gUw", text = "Type gUw." },
    },
    {
      id = "uppercase-to-end-with-gU$",
      instruction = "Normalize the log line: with the cursor at the start, uppercase everything to the end of the line with gU$.",
      initial_content = { "warn: disk full" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "WARN: DISK FULL" } },
      success_message = "gU$ uppercases from the cursor to the line end.",
      hints = {
        "Type g, U, and the $ key.",
        "$ is just a motion — gU works with any of them.",
      },
      solution = { keys = "gU$", text = "Type gU$." },
    },
    {
      id = "lowercase-whole-line-with-gug$",
      instruction = "The log line is screaming. With the cursor at the start of the line, lowercase the whole line with gug$.",
      initial_content = { "ERROR: MIGRATION FAILED" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "error: migration failed" } },
      success_message = "gug$ lowercases the line — a calm log line.",
      hints = {
        "Type g, u, g, $.",
        "The second g makes $ count as a motion after gu.",
      },
      solution = { keys = "gug$", text = "Type gug$." },
    },
    {
      id = "lowercase-inside-parens",
      instruction = "With the cursor on the 'M' of 'MAX_ATTEMPTS', lowercase what is inside the parentheses with gui(.",
      initial_content = { "retry(attempt(MAX_ATTEMPTS))" },
      cursor = { 1, 12 },
      validation = { type = "buffer", expected = { "retry(attempt(max_attempts))" } },
      success_message = "gui( combines a case change with a text object.",
      hints = {
        "Type g, u, i, and the open parenthesis.",
        "Text objects are motions too — gu/gU accept them.",
      },
      solution = { keys = "gui(", text = "Type gui(." },
    },
  },
}
