return {
  id = "dot-repeat",
  title = "The Dot Command",
  summary = ". repeats your last change; 2. and 3. repeat it several times.",
  concept = "Every change you make in normal mode — dw, cw, r, a typed character, even an insert-mode edit — can be repeated with the dot command. . replays the last change; a count before it (2., 5.) replays that many times. Fixing the same typo on three lines or adding semicolons to five statements is where the dot pays off.",
  exercises = {
    {
      id = "repeat-last-change",
      instruction = "Fix the typo 'Recieve' on line 1: change the word with ciw, type 'Receive', press <Esc>. Then go to line 2 with j and repeat the exact same change with a single dot.",
      initial_content = { "socket.Recieve(data)", "client.Recieve(event)" },
      cursor = { 1, 7 },
      validation = { type = "buffer", expected = { "socket.Receive(data)", "client.Receive(event)" } },
      success_message = ". repeats the last change at the new cursor position.",
      hints = {
        "ciw, type Receive, <Esc>, j, then press . once.",
        "The dot replays the whole change, not just one key.",
      },
      solution = { keys = "ciwReceive<Esc>j.", text = "Type ciwReceive, <Esc>, j, then dot." },
    },
    {
      id = "repeat-with-count",
      instruction = "Strip the build log line: delete the first word with dw, then repeat the deletion three more times with 3. until the line is empty.",
      initial_content = { "echo building api image" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "" } },
      success_message = "A count before the dot repeats the change that many times.",
      hints = {
        "Type dw, then 3, then dot.",
        "Each dot repetition acts at the current cursor position.",
      },
      solution = { keys = "dw3.", text = "Type dw, then 3." },
    },
    {
      id = "repeat-insertion-with-dot",
      instruction = "Both statements are missing a semicolon. Append one with A and ';', press <Esc>, then go to the next line with j and press . to add one there too.",
      initial_content = { "app.use(logger)", "app.use(auth)" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "app.use(logger);", "app.use(auth);" } },
      success_message = "Insert-mode edits are repeatable with the dot too.",
      hints = {
        "Press A, type ;, press <Esc>, then j, then dot.",
        "The dot remembers what you typed in insert mode.",
      },
      solution = { keys = "A;<Esc>j.", text = "Append ';', <Esc>, j, then dot." },
    },
    {
      id = "repeat-char-deletion",
      instruction = "The heading has two extra '#' characters. Delete the character under the cursor with x, then use 2. to remove the rest and the space.",
      initial_content = { "## Deploy" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "Deploy" } },
      success_message = "x, like every change, is repeatable with the dot.",
      hints = {
        "Type x, then 2, then dot.",
        "x deletes the character, the cursor stays put, and the next x hits the next character.",
      },
      solution = { keys = "x2.", text = "Type x, then 2." },
    },
  },
}
