return {
  id = "insert-advanced",
  title = "Inserting Like a Pro",
  summary = "I, A, O, s, r and S: insert and edit text without leaving normal mode first.",
  concept = "i inserts before the cursor, a after it. I inserts at the first non-blank character of the line (perfect for commenting indented code), A appends at the end. o opens a new line below, O above, and drops you into INSERT mode. s deletes the character under the cursor and inserts; r replaces exactly that one character; S deletes the whole line and inserts. <Esc> always returns to NORMAL mode.",
  exercises = {
    {
      id = "insert-at-line-start-with-I",
      instruction = "The line is indented. Press I to insert at the first non-blank character, type '// validate ', then <Esc>, so the line reads:     // validate if err != nil {",
      initial_content = { "    if err != nil {" },
      cursor = { 1, 4 },
      validation = { type = "buffer", expected = { "    // validate if err != nil {" } },
      success_message = "I inserts at the first non-blank character of the line.",
      hints = {
        "Press capital I, not i.",
        "I skips leading whitespace; i would insert under a space.",
      },
      solution = { keys = "I// validate <Esc>", text = "Press I, type '// validate ', press <Esc>." },
    },
    {
      id = "append-at-line-end-with-A",
      instruction = "The port is missing its last digit. Press A to append at the end of the line, type '0', then <Esc>.",
      initial_content = { "PORT ?= 808" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "PORT ?= 8080" } },
      success_message = "A appends after the last character of the line.",
      hints = {
        "Press capital A.",
        "A is like pressing $ then a.",
      },
      solution = { keys = "A0<Esc>", text = "Press A, type 0, press <Esc>." },
    },
    {
      id = "open-line-above-with-O",
      instruction = "The Dockerfile copies the whole context before the dependencies are installed. The cursor is on 'COPY . .'. Press O to open a new line ABOVE it, type 'COPY package.json ./', then <Esc>.",
      initial_content = { "FROM node:20", "COPY . .", 'CMD ["node", "server.js"]' },
      cursor = { 2, 0 },
      validation = {
        type = "buffer",
        expected = { "FROM node:20", "COPY package.json ./", "COPY . .", 'CMD ["node", "server.js"]' },
      },
      success_message = "O opens a line above; o opens one below.",
      hints = {
        "Press capital O.",
        "The new line appears above the cursor and you type in it.",
      },
      solution = { keys = "OCOPY package.json ./<Esc>", text = "Press O, type the COPY line, press <Esc>." },
    },
    {
      id = "delete-char-and-type-with-s",
      instruction = "The method is misspelled: 'loq'. With the cursor on the 'q', press s to delete that character and type 'g'.",
      initial_content = { 'console.loq("server up")' },
      cursor = { 1, 10 },
      validation = { type = "buffer", expected = { 'console.log("server up")' } },
      success_message = "s deletes the character under the cursor and enters INSERT mode.",
      hints = {
        "Press s, then type g.",
        "s is like x followed by i.",
      },
      solution = { keys = "sg", text = "Press s, type g." },
    },
    {
      id = "replace-char-with-r",
      instruction = "The Makefile port has a letter O instead of a zero. With the cursor on the 'O', press r and then '0' to replace that single character.",
      initial_content = { "PORT ?= 8O80" },
      cursor = { 1, 9 },
      validation = { type = "buffer", expected = { "PORT ?= 8080" } },
      success_message = "r replaces exactly one character, no insert mode.",
      hints = {
        "Type r, then 0.",
        "r does not enter insert mode — one key replaces one character.",
      },
      solution = { keys = "r0", text = "Press r, then 0." },
    },
    {
      id = "change-whole-line-with-S",
      instruction = "The comment is stale. Press S to delete the line under the cursor and enter INSERT mode, type '# now: deployed to k3s', then <Esc>.",
      initial_content = { "# old: used docker-compose" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "# now: deployed to k3s" } },
      success_message = "S changes the whole line (cc).",
      hints = {
        "Press capital S.",
        "S is the same as cc.",
      },
      solution = { keys = "S# now: deployed to k3s<Esc>", text = "Press S, type the new comment, press <Esc>." },
    },
  },
}
