return {
  id = "insert-advanced",
  title = "Inserting Like a Pro",
  summary = "I, A, O, s, r and S: insert and edit text without leaving normal mode first.",
  concept = "i inserts before the cursor, a after it. I inserts at the first non-blank character of the line, A appends at the end. o opens a new line below, O above, and drops you into INSERT mode. s deletes the character under the cursor and inserts; r replaces exactly that one character; S deletes the whole line and inserts. <Esc> always returns to NORMAL mode.",
  exercises = {
    {
      id = "insert-at-line-start-with-I",
      instruction = "The line starts with two spaces. Press I to insert at the first non-blank character, type 'Hi ', then <Esc>.",
      initial_content = { "  hello" },
      cursor = { 1, 2 },
      validation = { type = "buffer", expected = { "  Hi hello" } },
      success_message = "I inserts at the first non-blank character of the line.",
      hints = {
        "Press capital I, not i.",
        "I skips leading whitespace; i would insert under the space.",
      },
      solution = { keys = "IHi <Esc>", text = "Press I, type 'Hi ', press <Esc>." },
    },
    {
      id = "append-at-line-end-with-A",
      instruction = "Press A to append at the end of the line, type ' 1.0', then <Esc>.",
      initial_content = { "release" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "release 1.0" } },
      success_message = "A appends after the last character of the line.",
      hints = {
        "Press capital A.",
        "A is like pressing $ then a.",
      },
      solution = { keys = "A 1.0<Esc>", text = "Press A, type ' 1.0', press <Esc>." },
    },
    {
      id = "open-line-above-with-O",
      instruction = "The cursor is on 'bottom'. Press O to open a new line ABOVE it, type 'mid', then <Esc>.",
      initial_content = { "top", "bottom" },
      cursor = { 2, 0 },
      validation = { type = "buffer", expected = { "top", "mid", "bottom" } },
      success_message = "O opens a line above; o opens one below.",
      hints = {
        "Press capital O.",
        "The new line appears above the cursor and you type in it.",
      },
      solution = { keys = "Omid<Esc>", text = "Press O, type 'mid', press <Esc>." },
    },
    {
      id = "delete-char-and-type-with-s",
      instruction = "With the cursor on the 'x', press s to delete that character and type 'r'.",
      initial_content = { "the caxt sat" },
      cursor = { 1, 6 },
      validation = { type = "buffer", expected = { "the cart sat" } },
      success_message = "s deletes the character under the cursor and enters INSERT mode.",
      hints = {
        "Press s, then type r.",
        "s is like x followed by i.",
      },
      solution = { keys = "sr", text = "Press s, type r." },
    },
    {
      id = "replace-char-with-r",
      instruction = "With the cursor on 's', press r and then 't' to replace that single character.",
      initial_content = { "sall right" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "tall right" } },
      success_message = "r replaces exactly one character, no insert mode.",
      hints = {
        "Type r, then t.",
        "r does not enter insert mode — one key replaces one character.",
      },
      solution = { keys = "rt", text = "Press r, then t." },
    },
    {
      id = "change-whole-line-with-S",
      instruction = "Press S to delete the line under the cursor and enter INSERT mode, type 'new line', then <Esc>.",
      initial_content = { "old line", "keep" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "new line", "keep" } },
      success_message = "S changes the whole line (cc).",
      hints = {
        "Press capital S.",
        "S is the same as cc.",
      },
      solution = { keys = "Snew line<Esc>", text = "Press S, type 'new line', press <Esc>." },
    },
  },
}
