return {
  id = "moving-around",
  title = "Moving Around",
  summary = "h, j, k, l move like arrow keys; 0, $, gg, G jump to line and file boundaries.",
  concept = "h, j, k, l move left, down, up, right. 0 and $ jump to the start and end of the line. gg and G jump to the top and bottom of the file. Prefix any motion with a number to repeat it: jj is two lines down.",
  exercises = {
    {
      id = "move-right-with-l",
      instruction = "Move the cursor to the last character of the line using only l. Do not type any text.",
      initial_content = { "Hello" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 4 } },
      success_message = "l moves the cursor one character to the right.",
      hints = {
        "Press l to move right one character.",
        "'Hello' has 5 characters, so press l four times.",
      },
      solution = { keys = "llll", text = "Press l four times." },
    },
    {
      id = "move-down-with-j",
      instruction = "Move the cursor to the beginning of the third line using only j.",
      initial_content = { "first", "second", "third" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 3, 0 } },
      success_message = "j moves the cursor one line down.",
      hints = {
        "Press j to move down one line.",
        "You are on line 1, so press j twice.",
      },
      solution = { keys = "jj", text = "Press j twice." },
    },
    {
      id = "start-of-line-with-0",
      instruction = "The cursor is at the end of the line. Press 0 (zero) to jump to the very start of the line.",
      initial_content = { "The quick brown fox" },
      cursor = { 1, 18 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 0 } },
      success_message = "0 jumps to column 0 of the line.",
      hints = {
        "Press the 0 key (on the number row, not the numpad).",
      },
      solution = { keys = "0", text = "Press 0." },
    },
    {
      id = "end-of-line-with-dollar",
      instruction = "The cursor is at the start of the line. Press $ to jump to the last character of the line.",
      initial_content = { "The quick brown fox" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 18 } },
      success_message = "$ jumps to the end of the line.",
      hints = {
        "Press the $ key (shift + 4).",
      },
      solution = { keys = "$", text = "Press $." },
    },
    {
      id = "top-of-file-with-gg",
      instruction = "Press gg to jump to the first line of the file.",
      initial_content = { "line one", "line two", "line three", "line four", "line five" },
      cursor = { 3, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 0 } },
      success_message = "gg jumps to the top of the file.",
      hints = {
        "Press g twice in quick succession.",
      },
      solution = { keys = "gg", text = "Press gg." },
    },
    {
      id = "bottom-of-file-with-G",
      instruction = "Press G (capital) to jump to the last line of the file.",
      initial_content = { "line one", "line two", "line three", "line four", "line five" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 5, 0 } },
      success_message = "G jumps to the bottom of the file.",
      hints = {
        "Press capital G (shift + g).",
      },
      solution = { keys = "G", text = "Press G." },
    },
    {
      id = "counted-moves",
      instruction = "Move 2 lines down and 3 characters to the right, ending on the 'e' of 'three'. Try counts: 2j then 3l.",
      initial_content = { "one", "two", "three", "four" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 3, 3 } },
      success_message = "Counts multiply the motion that follows them.",
      hints = {
        "Type 2j to move down two lines at once.",
        "Then type 3l to move right three characters.",
      },
      solution = { keys = "2j3l", text = "Press 2j, then 3l." },
    },
  },
}
