return {
  id = "operators",
  title = "Operators",
  summary = "Operators like d (delete), c (change), y (yank) combine with motions and objects.",
  concept = "An operator acts on the text a motion covers. d deletes, c deletes and opens INSERT mode, y yanks (copies) into the register, p puts the register after the cursor. d$ and D delete to the end of the line, C changes to the end of the line, dd deletes the whole line, and ~ swaps the case of a character. u undoes the last change. The exercises run on Go, YAML and a shell-style file.",
  exercises = {
    {
      id = "delete-line-with-dd",
      instruction = "Delete the stale TODO comment line entirely using dd.",
      initial_content = {
        "// TODO: add retry with backoff",
        'conn, err := sql.Open("postgres", dsn)',
      },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { 'conn, err := sql.Open("postgres", dsn)' } },
      success_message = "dd deletes the whole line the cursor is on.",
      hints = {
        "Press d twice in quick succession.",
      },
      solution = { keys = "dd", text = "Press dd." },
    },
    {
      id = "delete-to-eol-with-d-dollar",
      instruction = "With the cursor on the '/' of the trailing comment, press d$ to delete from the cursor to the end of the line.",
      initial_content = { "port := 8080 // TODO: move to config" },
      cursor = { 1, 13 },
      validation = { type = "buffer", expected = { "port := 8080" } },
      success_message = "d$ deletes to the end of the line.",
      hints = {
        "Type d, then $.",
        "Everything from the cursor to the line end is removed.",
      },
      solution = { keys = "d$", text = "Type d, then $." },
    },
    {
      id = "delete-to-eol-with-D",
      instruction = "With the cursor on the space before '// entrypoint', press D (delete to end of line) so the line reads: func main() {",
      initial_content = { "func main() { // entrypoint" },
      cursor = { 1, 13 },
      validation = { type = "buffer", expected = { "func main() {" } },
      success_message = "D is a shorthand for d$.",
      hints = {
        "Press capital D.",
      },
      solution = { keys = "D", text = "Press D." },
    },
    {
      id = "change-word-with-cw",
      instruction = "Rename the variable: with the cursor on the 'r' of 'retries', press cw to delete the word and enter INSERT mode. Type maxRetries, then press <Esc>. The line must read: maxRetries := 3",
      initial_content = { "retries := 3" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "maxRetries := 3" } },
      success_message = "cw changes (deletes + inserts) from the cursor to the next word.",
      hints = {
        "Type cw, then type maxRetries.",
        "Press <Esc> when done.",
      },
      solution = { keys = "cwmaxRetries<Esc>", text = "Type cw, type maxRetries, press <Esc>." },
    },
    {
      id = "change-to-eol-with-C",
      instruction = "Bump the version: press C to delete from the cursor to the end of the line and enter INSERT mode. Retype the line so it reads: const version = \"1.0\"",
      initial_content = { 'const version = "0.9"' },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { 'const version = "1.0"' } },
      success_message = "C is a shorthand for c$.",
      hints = {
        "Press capital C.",
        "Type 'const version = \"1.0\"' then press <Esc>.",
      },
      solution = { keys = 'Cconst version = "1.0"<Esc>', text = "Press C, type the new line, press <Esc>." },
    },
    {
      id = "yank-line-and-put-with-yyp",
      instruction = "Duplicate the compose setting: yank the line under the cursor with yy, then put a copy below it with p. The register must hold: retries: 3",
      initial_content = { "  retries: 3" },
      cursor = { 1, 0 },
      validation = {
        type = "composite",
        validations = {
          { type = "buffer", expected = { "  retries: 3", "  retries: 3" } },
          { type = "register", expected = "retries: 3" },
        },
      },
      success_message = "yy yanks the line into the register, p puts it after the cursor.",
      hints = {
        "Press y twice (yy) to yank the current line.",
        "Press p to put the yanked line below.",
      },
      solution = { keys = "yyp", text = "Press y twice (yy), then p." },
    },
    {
      id = "swap-case-with-tilde",
      instruction = "The flag should be unexported. Press ~ to swap the case of the character under the cursor so the line reads: isDev := true",
      initial_content = { "IsDev := true" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "isDev := true" } },
      success_message = "~ toggles the case of a character.",
      hints = {
        "Press the ~ key (shift + backtick).",
      },
      solution = { keys = "~", text = "Press ~." },
    },
    {
      id = "undo-with-u",
      instruction = "You accidentally typed an extra '!' at the end of the line. Make the mistake (press A, type !, <Esc>), then undo the whole change with u so the line is back to: log.Fatal(err)",
      file = true,
      initial_content = { "log.Fatal(err)" },
      cursor = { 1, 0 },
      validation = {
        type = "composite",
        validations = {
          { type = "buffer", expected = { "log.Fatal(err)" } },
          { type = "sequence", allowed = { { "u" } } },
        },
      },
      success_message = "u undoes your last change.",
      hints = {
        "First create the mistake: press A, type !, press <Esc>.",
        "Then press u to undo it.",
      },
      solution = { keys = "A!<Esc>u", text = "Press A, type !, press <Esc>, then press u." },
    },
  },
}
