return {
  id = "text-objects",
  title = "Text Objects",
  summary = "i and a combine operators with structures: i\" inside quotes, a( around parens, diw the word.",
  concept = "A text object names a piece of text by its structure. Prefix it with an operator: d\" deletes it, c\" changes it, v\" selects it. i means inside (keep the delimiters), a means around (include the delimiters). Common objects: \" ' ( ) [ { and w (word).",
  exercises = {
    {
      id = "delete-inside-quotes",
      instruction = "Press di\" to delete the text inside the double quotes, keeping the quotes themselves. The line must read: print \"\" ",
      initial_content = { 'print "hello"' },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { 'print ""' } },
      success_message = "di\" deletes the text inside the quotes.",
      hints = {
        "Type d, i, then the double-quote key.",
        "The quotes stay; only what is between them is deleted.",
      },
      solution = { keys = 'di"', text = "Type di\"." },
    },
    {
      id = "delete-around-quotes",
      instruction = "Press da\" to delete the quotes and everything between them. The line must read: say",
      initial_content = { 'say "hi"' },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "say" } },
      success_message = "da\" deletes the quotes and their content.",
      hints = {
        "Type d, a, then the double-quote key.",
        "a includes the delimiters themselves.",
      },
      solution = { keys = 'da"', text = "Type da\"." },
    },
    {
      id = "change-inside-parens",
      instruction = "Press ci( to delete the text inside the parentheses and enter INSERT mode. Type 42, then press <Esc>. The line must read: f(42)",
      initial_content = { "f(1 + 2)" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "f(42)" } },
      success_message = "ci( changes the text inside the parentheses.",
      hints = {
        "Type c, i, then (.",
        "Type 42, then press <Esc>.",
      },
      solution = { keys = "ci(42<Esc>", text = "Type ci(, type 42, press <Esc>." },
    },
    {
      id = "delete-word-with-diw",
      instruction = "With the cursor on the 'c' of 'cat', press diw to delete just the word. The line must read: delete the word",
      initial_content = { "delete the word cat" },
      cursor = { 1, 16 },
      validation = {
        type = "composite",
        validations = {
          { type = "buffer", expected = { "delete the word" } },
          { type = "register", expected = "cat" },
        },
      },
      success_message = "diw deletes the word under the cursor and yanks it.",
      hints = {
        "Type d, i, w.",
        "iw is the word under the cursor, without surrounding spaces.",
      },
      solution = { keys = "diw", text = "Type diw." },
    },
    {
      id = "change-inside-single-quotes",
      instruction = "Press ci' to delete the text inside the single quotes and enter INSERT mode. Type Alice, then press <Esc>. The line must read: name = 'Alice'",
      initial_content = { "name = 'Bob'" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "name = 'Alice'" } },
      success_message = "ci' changes the text inside single quotes.",
      hints = {
        "Type c, i, then the single-quote key.",
        "Type Alice, then press <Esc>.",
      },
      solution = { keys = "ci'Alice<Esc>", text = "Type ci', type Alice, press <Esc>." },
    },
    {
      id = "delete-paragraph-with-dip",
      instruction = "The cursor is on the second paragraph. Press dip to delete it, leaving only the first paragraph.",
      initial_content = { "first para", "", "second para" },
      cursor = { 3, 0 },
      validation = { type = "buffer", expected = { "first para" } },
      success_message = "dip deletes the paragraph under the cursor.",
      hints = {
        "Type d, i, p.",
        "A paragraph is a block of lines separated by blank lines.",
      },
      solution = { keys = "dip", text = "Type dip." },
    },
    {
      id = "select-word-with-viw",
      instruction = "Select the word 'hello' (but not the trailing space) with viw. Stay in VISUAL mode.",
      initial_content = { "hello world" },
      cursor = { 1, 0 },
      validation = {
        type = "selection",
        start = { 1, 0 },
        finish = { 1, 4 },
      },
      success_message = "viw selects the word under the cursor in VISUAL mode.",
      hints = {
        "Type v, i, w.",
        "The selection should cover exactly h-e-l-l-o.",
      },
      solution = { keys = "viw", text = "Type viw." },
    },
  },
}
