return {
  id = "text-objects",
  title = "Text Objects",
  summary = "i and a combine operators with structures: i\" inside quotes, a( around parens, diw the word.",
  concept = "A text object names a piece of text by its structure. Prefix it with an operator: d\" deletes it, c\" changes it, v\" selects it. i means inside (keep the delimiters), a means around (include the delimiters). Common objects: \" ' ( ) [ { and w (word). In code, quotes and parens are everywhere — text objects are the fastest way to edit inside them.",
  exercises = {
    {
      id = "delete-inside-quotes",
      instruction = "Press di\" to delete the text inside the double quotes, keeping the quotes themselves. The line must read: console.log(\"\")",
      initial_content = { 'console.log("loading...")' },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { 'console.log("")' } },
      success_message = "di\" deletes the text inside the quotes.",
      hints = {
        "Type d, i, then the double-quote key.",
        "The quotes stay; only what is between them is deleted.",
      },
      solution = { keys = 'di"', text = "Type di\"." },
    },
    {
      id = "delete-around-quotes",
      instruction = "Drop the whole string literal: press da\" to delete the quotes and everything between them. The line must read: const label =",
      initial_content = { 'const label = "TODO: remove"' },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "const label =" } },
      success_message = "da\" deletes the quotes and their content.",
      hints = {
        "Type d, a, then the double-quote key.",
        "a includes the delimiters themselves.",
      },
      solution = { keys = 'da"', text = "Type da\"." },
    },
    {
      id = "change-inside-parens",
      instruction = "Swap the middleware: with the cursor on the 'm' of 'middleware', press ci( to delete the text inside the parentheses and enter INSERT mode. Type auth, then press <Esc>. The line must read: app.use(auth)",
      initial_content = { "app.use(middleware)" },
      cursor = { 1, 8 },
      validation = { type = "buffer", expected = { "app.use(auth)" } },
      success_message = "ci( changes the text inside the parentheses.",
      hints = {
        "Type c, i, then (.",
        "Type auth, then press <Esc>.",
      },
      solution = { keys = "ci(auth<Esc>", text = "Type ci(, type auth, press <Esc>." },
    },
    {
      id = "delete-word-with-diw",
      instruction = "With the cursor on the 'b' of 'boom', press diw to delete just the word, keeping the quotes. The line must read: return fmt.Errorf(\"\")",
      initial_content = { 'return fmt.Errorf("boom")' },
      cursor = { 1, 19 },
      validation = {
        type = "composite",
        validations = {
          { type = "buffer", expected = { 'return fmt.Errorf("")' } },
          { type = "register", expected = "boom" },
        },
      },
      success_message = "diw deletes the word under the cursor and yanks it.",
      hints = {
        "Type d, i, w.",
        "iw is the word under the cursor, without surrounding spaces.",
      },
      solution = { keys = "diw", text = "Type diw." },
    },
    {
      id = "change-inside-single-quotes",
      instruction = "Change the Ruby string: press ci' to delete the text inside the single quotes and enter INSERT mode. Type service, then press <Esc>. The line must read: name = 'service'",
      initial_content = { "name = 'root'" },
      cursor = { 1, 0 },
      validation = { type = "buffer", expected = { "name = 'service'" } },
      success_message = "ci' changes the text inside single quotes.",
      hints = {
        "Type c, i, then the single-quote key.",
        "Type service, then press <Esc>.",
      },
      solution = { keys = "ci'service<Esc>", text = "Type ci', type service, press <Esc>." },
    },
    {
      id = "delete-paragraph-with-dip",
      instruction = "The cursor is on the deploy command in the README. Press dip to delete that paragraph, leaving only the heading.",
      initial_content = { "# Deploy", "", "k3s kubectl apply -f deploy/" },
      cursor = { 3, 0 },
      validation = { type = "buffer", expected = { "# Deploy" } },
      success_message = "dip deletes the paragraph under the cursor.",
      hints = {
        "Type d, i, p.",
        "A paragraph is a block of lines separated by blank lines.",
      },
      solution = { keys = "dip", text = "Type dip." },
    },
    {
      id = "select-word-with-viw",
      instruction = "Select the identifier 'port' (but not the trailing space) with viw. Stay in VISUAL mode.",
      initial_content = { "var port = 8080" },
      cursor = { 1, 4 },
      validation = {
        type = "selection",
        start = { 1, 4 },
        finish = { 1, 7 },
      },
      success_message = "viw selects the word under the cursor in VISUAL mode.",
      hints = {
        "Type v, i, w.",
        "The selection should cover exactly p-o-r-t.",
      },
      solution = { keys = "viw", text = "Type viw." },
    },
  },
}
