return {
  id = "visual-mode",
  title = "Visual Mode",
  summary = "Select text with v, V or <C-v>, extend the selection, then delete, change or transform it.",
  concept = "VISUAL mode selects text. Press v for charwise, V for linewise (whole lines), <C-v> for blockwise (a rectangle). Extend or shrink the selection with the motions you already know: h j k l, w, 0, $. Then act on it: d deletes, c changes (delete + insert), y yanks, x deletes, u and U change the case. <Esc> leaves VISUAL mode.",
  exercises = {
    {
      id = "select-chars-with-v",
      instruction = "With the cursor on the 'h' of 'hello', press v to start charwise VISUAL mode, then l to extend the selection so it covers exactly 'he'.",
      initial_content = { "hello" },
      cursor = { 1, 0 },
      validation = {
        type = "selection",
        start = { 1, 0 },
        finish = { 1, 1 },
      },
      success_message = "v starts charwise selection; l extends it one character.",
      hints = {
        "Press v, then l once.",
        "The selection grows from the cursor as you move.",
      },
      solution = { keys = "vl", text = "Press v, then l." },
    },
    {
      id = "select-whole-line-with-V",
      instruction = "Press V to select the entire line (linewise VISUAL mode). Stay in VISUAL mode.",
      initial_content = { "hello world" },
      cursor = { 1, 0 },
      validation = {
        type = "selection",
        start = { 1, 0 },
        finish = { 1, 10 },
      },
      success_message = "V selects whole lines; the cursor column doesn't matter.",
      hints = {
        "Press capital V.",
        "Linewise selection always spans the full line.",
      },
      solution = { keys = "V", text = "Press V." },
    },
    {
      id = "blockwise-select-columns",
      instruction = "Press <C-v> for blockwise VISUAL mode, then l and j, so the block covers the first two columns of both lines. Stay in VISUAL mode.",
      initial_content = { "apple", "banana" },
      cursor = { 1, 0 },
      validation = {
        type = "selection",
        start = { 1, 0 },
        finish = { 2, 1 },
      },
      success_message = "<C-v> selects a rectangle; l and j grow it in both directions.",
      hints = {
        "Control-v enters blockwise selection.",
        "Move right with l, down with j — the block follows as a rectangle.",
      },
      solution = { keys = "<C-v>lj", text = "Press <C-v>, then l, then j." },
    },
    {
      id = "delete-a-selection",
      instruction = "With the cursor on the 'c' of 'cat', select the word with viw and delete the selection with d.",
      initial_content = { "keep cat" },
      cursor = { 1, 5 },
      validation = { type = "buffer", expected = { "keep" } },
      success_message = "d deletes whatever the selection covers.",
      hints = {
        "Type viw to select the word, then d.",
        "In VISUAL mode an operator acts on the selection.",
      },
      solution = { keys = "viwd", text = "Type viw, then d." },
    },
    {
      id = "change-a-selection",
      instruction = "With the cursor on the 'c' of 'cats', select the word with viw and change it with c: type dogs, then <Esc>.",
      initial_content = { "I like cats" },
      cursor = { 1, 7 },
      validation = { type = "buffer", expected = { "I like dogs" } },
      success_message = "c deletes the selection and opens INSERT mode at its start.",
      hints = {
        "Type viwc — the selection is replaced by what you type.",
        "Press <Esc> when done.",
      },
      solution = { keys = "viwcdogs<Esc>", text = "Type viwc, type dogs, press <Esc>." },
    },
    {
      id = "delete-a-line-visually",
      instruction = "The cursor is on the second line. Select the line with V and delete it with d.",
      initial_content = { "first", "second", "third" },
      cursor = { 2, 0 },
      validation = { type = "buffer", expected = { "first", "third" } },
      success_message = "Vd deletes the whole line under the cursor.",
      hints = {
        "Press V, then d.",
        "That's the visual equivalent of dd.",
      },
      solution = { keys = "Vd", text = "Press V, then d." },
    },
    {
      id = "uppercase-a-selection",
      instruction = "With the cursor on the 't' of 'this', select the word with viw and change its case to UPPER with U.",
      initial_content = { "make this loud" },
      cursor = { 1, 5 },
      validation = { type = "buffer", expected = { "make THIS loud" } },
      success_message = "U uppercases the selection; u lowercases it.",
      hints = {
        "Type viwU.",
        "u and U change case without deleting.",
      },
      solution = { keys = "viwU", text = "Type viw, then U." },
    },
  },
}
