return {
  id = "visual-mode",
  title = "Visual Mode",
  summary = "Select text with v, V or <C-v>, extend the selection, then delete, change or transform it.",
  concept = "VISUAL mode selects text. Press v for charwise, V for linewise (whole lines), <C-v> for blockwise (a rectangle). Extend or shrink the selection with the motions you already know: h j k l, w, 0, $. Then act on it: d deletes, c changes (delete + insert), y yanks, u and U change the case. <Esc> leaves VISUAL mode. The exercises run on Go imports, YAML and JS.",
  exercises = {
    {
      id = "select-chars-with-v",
      instruction = "With the cursor on the 'v' of 'var', press v to start charwise VISUAL mode, then l to extend the selection so it covers exactly 'va'.",
      initial_content = { "var port = 8080" },
      cursor = { 1, 0 },
      validation = {
        type = "selection",
        start = { 1, 0 },
        finish = { 1, 1 },
      },
      success_message = "v starts charwise selection; l extends it one character.",
      hints = {
        "Press v, then l once.",
        "The selection grows from the cursor as you move.",
      },
      solution = { keys = "vl", text = "Press v, then l." },
    },
    {
      id = "select-whole-line-with-V",
      instruction = "Press V to select the entire line (linewise VISUAL mode). Stay in VISUAL mode.",
      initial_content = { "db, err := gorm.Open(dsn, cfg)" },
      cursor = { 1, 0 },
      validation = {
        type = "selection",
        start = { 1, 0 },
        finish = { 1, 29 },
      },
      success_message = "V selects whole lines; the cursor column doesn't matter.",
      hints = {
        "Press capital V.",
        "Linewise selection always spans the full line.",
      },
      solution = { keys = "V", text = "Press V." },
    },
    {
      id = "blockwise-select-columns",
      instruction = "Press <C-v> for blockwise VISUAL mode, then l and j, so the block covers the first two columns of both lines. Stay in VISUAL mode.",
      initial_content = { "name: api", "image: api:1.2" },
      cursor = { 1, 0 },
      validation = {
        type = "selection",
        start = { 1, 0 },
        finish = { 2, 1 },
      },
      success_message = "<C-v> selects a rectangle; l and j grow it in both directions.",
      hints = {
        "Control-v enters blockwise selection.",
        "Move right with l, down with j — the block follows as a rectangle.",
      },
      solution = { keys = "<C-v>lj", text = "Press <C-v>, then l, then j." },
    },
    {
      id = "delete-a-selection",
      instruction = "With the cursor on the 'd' of 'debug', select the word with viw and delete the selection with d.",
      initial_content = { 'value := getFlag("debug")' },
      cursor = { 1, 18 },
      validation = { type = "buffer", expected = { 'value := getFlag("")' } },
      success_message = "d deletes whatever the selection covers.",
      hints = {
        "Type viw to select the word, then d.",
        "In VISUAL mode an operator acts on the selection.",
      },
      solution = { keys = "viwd", text = "Type viw, then d." },
    },
    {
      id = "change-a-selection",
      instruction = "With the cursor on the 'c' of 'cats', select the word with viw and change it with c: type users, then <Esc>.",
      initial_content = { 'client.Get("/cats")' },
      cursor = { 1, 13 },
      validation = { type = "buffer", expected = { 'client.Get("/users")' } },
      success_message = "c deletes the selection and opens INSERT mode at its start.",
      hints = {
        "Type viwc — the selection is replaced by what you type.",
        "Press <Esc> when done.",
      },
      solution = { keys = "viwcusers<Esc>", text = "Type viwc, type users, press <Esc>." },
    },
    {
      id = "delete-a-line-visually",
      instruction = "The cursor is on the unused import. Select the line with V and delete it with d.",
      initial_content = { 'import "fmt"', 'import "os"', 'import "net/http"', "main()" },
      cursor = { 2, 0 },
      validation = { type = "buffer", expected = { 'import "fmt"', 'import "net/http"', "main()" } },
      success_message = "Vd deletes the whole line under the cursor.",
      hints = {
        "Press V, then d.",
        "That's the visual equivalent of dd.",
      },
      solution = { keys = "Vd", text = "Press V, then d." },
    },
    {
      id = "uppercase-a-selection",
      instruction = "With the cursor on the 't' of 'this', select the word with viw and change its case to UPPER with U.",
      initial_content = { 'fmt.Println("make this loud")' },
      cursor = { 1, 18 },
      validation = { type = "buffer", expected = { 'fmt.Println("make THIS loud")' } },
      success_message = "U uppercases the selection; u lowercases it.",
      hints = {
        "Type viwU.",
        "u and U change case without deleting.",
      },
      solution = { keys = "viwU", text = "Type viw, then U." },
    },
  },
}
