return {
  id = "word-motions",
  title = "Word Motions",
  summary = "w, b, e jump by word; W jumps by big word; f and t find a character; ; repeats the last search.",
  concept = "w jumps forward to the start of the next word, b back to the start of the previous word, e to the end of the current or next word. W and B ignore punctuation and jump between blocks of non-blank characters — useful in code. f<char> jumps to the next occurrence of a character, t<char> stops just before it, and ; repeats the last f or t. The exercises run on Go and SQL.",
  exercises = {
    {
      id = "forward-one-word-with-w",
      instruction = "Press w to jump the cursor to the start of the next word ('h' of 'handle').",
      initial_content = { "func handle(ctx context.Context) error {" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 5 } },
      success_message = "w jumps forward to the start of the next word.",
      hints = {
        "Press w once.",
      },
      solution = { keys = "w", text = "Press w." },
    },
    {
      id = "back-one-word-with-b",
      instruction = "The cursor is on the last 'r' of 'err'. Press b to jump back to the start of the word 'err' ('e').",
      initial_content = { "return err" },
      cursor = { 1, 9 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 7 } },
      success_message = "b jumps back to the start of the previous word.",
      hints = {
        "Press b once.",
      },
      solution = { keys = "b", text = "Press b." },
    },
    {
      id = "end-of-word-with-e",
      instruction = "Press e to jump to the end of the word 'port' (on the 't').",
      initial_content = { "port := 8080" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 3 } },
      success_message = "e jumps to the end of the current word.",
      hints = {
        "Press e once.",
      },
      solution = { keys = "e", text = "Press e." },
    },
    {
      id = "big-word-with-W",
      instruction = "Punctuation does not stop big words. Press W to jump past 'SELECT' to the start of 'id'.",
      initial_content = { "SELECT id, email FROM users;" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 7 } },
      success_message = "W jumps between blocks of non-blank characters.",
      hints = {
        "Press capital W (shift + w).",
        "W treats 'SELECT' and 'id,' as single blocks.",
      },
      solution = { keys = "W", text = "Press W." },
    },
    {
      id = "find-char-with-f",
      instruction = "Press f then ( to jump to the first opening parenthesis after the cursor.",
      initial_content = { "db.Query(ctx, q)" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 8 } },
      success_message = "f<char> jumps to the next occurrence of that character.",
      hints = {
        "Type f, then the ( key.",
        "Look for the first ( after the cursor.",
      },
      solution = { keys = "f(", text = "Type f, then (." },
    },
    {
      id = "before-char-with-t",
      instruction = "Press t then ( to stop just before the first opening parenthesis (on the 'y' of 'Query').",
      initial_content = { "db.Query(ctx, q)" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 7 } },
      success_message = "t<char> stops one character before the target.",
      hints = {
        "Type t, then the ( key.",
        "You should land on the 'y' of 'Query'.",
      },
      solution = { keys = "t(", text = "Type t, then (." },
    },
    {
      id = "repeat-last-f-with-semicolon",
      instruction = "First jump to the first '(' with f, then press ; to repeat it and land on the second '(' (the one after Errorf).",
      initial_content = { 'log.Error(fmt.Errorf("x %v", err))' },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 20 } },
      success_message = "; repeats your last f or t in the same direction.",
      hints = {
        "Type f( to find the first opening parenthesis.",
        "Press ; to jump to the following one (after Errorf).",
      },
      solution = { keys = "f(;", text = "Type f(, then ;." },
    },
  },
}
