return {
  id = "word-motions",
  title = "Word Motions",
  summary = "w, b, e jump by word; W jumps by big word; f and t find a character; ; repeats the last search.",
  concept = "w jumps forward to the start of the next word, b back to the start of the previous word, e to the end of the current or next word. W and B ignore punctuation and jump between blocks of non-blank characters. f<char> jumps to the next occurrence of a character, t<char> stops just before it, and ; repeats the last f or t.",
  exercises = {
    {
      id = "forward-one-word-with-w",
      instruction = "Press w to jump the cursor to the start of the next word ('q').",
      initial_content = { "The quick brown fox" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 4 } },
      success_message = "w jumps forward to the start of the next word.",
      hints = {
        "Press w once.",
      },
      solution = { keys = "w", text = "Press w." },
    },
    {
      id = "back-one-word-with-b",
      instruction = "The cursor is on the 'x'. Press b to jump back to the start of the word 'fox' ('f').",
      initial_content = { "The quick brown fox" },
      cursor = { 1, 18 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 16 } },
      success_message = "b jumps back to the start of the previous word.",
      hints = {
        "Press b once.",
      },
      solution = { keys = "b", text = "Press b." },
    },
    {
      id = "end-of-word-with-e",
      instruction = "Press e to jump to the end of the word 'The' (on the 'e').",
      initial_content = { "The quick brown fox" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 2 } },
      success_message = "e jumps to the end of the current word.",
      hints = {
        "Press e once.",
      },
      solution = { keys = "e", text = "Press e." },
    },
    {
      id = "big-word-with-W",
      instruction = "Punctuation does not stop big words. Press W to jump past 'hello,' to the start of 'world!' (on the 'w').",
      initial_content = { "hello, world! foo" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 7 } },
      success_message = "W jumps between blocks of non-blank characters.",
      hints = {
        "Press capital W (shift + w).",
        "W treats 'hello,' as one big word.",
      },
      solution = { keys = "W", text = "Press W." },
    },
    {
      id = "find-char-with-f",
      instruction = "Press f then o to jump to the first 'o' after the cursor.",
      initial_content = { "The quick brown fox" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 12 } },
      success_message = "f<char> jumps to the next occurrence of that character.",
      hints = {
        "Type f, then type o.",
        "Look for the first 'o' after the cursor.",
      },
      solution = { keys = "fo", text = "Type f, then o." },
    },
    {
      id = "before-char-with-t",
      instruction = "Press t then o to stop just before the first 'o' after the cursor (on the 'r').",
      initial_content = { "The quick brown fox" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 11 } },
      success_message = "t<char> stops one character before the target.",
      hints = {
        "Type t, then type o.",
        "You should land on the 'r' of 'brown'.",
      },
      solution = { keys = "to", text = "Type t, then o." },
    },
    {
      id = "repeat-last-f-with-semicolon",
      instruction = "First jump to the first 'o' with f, then press ; to repeat it and land on the next 'o'.",
      initial_content = { "The quick brown fox" },
      cursor = { 1, 0 },
      show_target = true,
      validation = { type = "cursor_position", position = { 1, 17 } },
      success_message = "; repeats your last f or t in the same direction.",
      hints = {
        "Type fo to find the first 'o'.",
        "Press ; to jump to the following 'o' (in 'fox').",
      },
      solution = { keys = "fo;", text = "Type fo, then ;." },
    },
  },
}
